### PR TITLE
Automatically install podman from https://unifi.boostchicken.io

### PR DESCRIPTION
**Pull request by bennettp123**
I've automated installing podman on UDM FW 2.4.x.

Not sure how I'm going to test persistence across firmware updates, nor UDMSE/UDMPro—I may just wait for ubnt to push a new firmware version and see what happens before taking this PR out of draft 🙃 

It should at least be safe to run on FW 1.x—it does nothing if podman is already installed, and it completely refuses to run if it finds a `unifi-os` command.

### CODE REVIEW

**Comment by boostchicken** [comment]
Wow @bennettp123.  Nicely done.  Does Podman work on 2.4.x?  I heard it was missing some kernel stuff.  Also you ready for this to be merged?

**Comment by operinko** [comment]
I never managed to get the podman build from https://unifi.boostchicken.io to work properly on my UDM Pro, but the build from unifi-blueberry-addon repo (via deb package) works fine despite throwing `WARN[0000] Failed to read current user namespace mappings` on every command.

**Comment by boostchicken** [comment]
Which build did you use, I believe the builds are largely the same

**Comment by operinko** [comment]
I tried both of them, I recall having some container storage-related issues (ERRO[0000] Failed to GetDriver graph btrfs) on them.
Following some guides to swap that to vfs graphs did get rid of the error, but containers would appear to start but nothing ever appeared in `podman ps` for me.

**Comment by GY8VSdYYzvL8-K6T** [comment]
> I tried both of them, I recall having some container storage-related issues (ERRO[0000] Failed to GetDriver graph btrfs) on them. Following some guides to swap that to vfs graphs did get rid of the error, but containers would appear to start but nothing ever appeared in `podman ps` for me.

But did unifi-blueberry-addon allow for installation of Podman and allow to make on-boot scripts functional on boot despite throwing errors?\?

**Comment by operinko** [comment]
It did, yes.

**Comment by operinko** [comment]
It did, yes

pe 27. tammik. 2023 klo 8.15 GY8VSdYYzvL8-K6T ***@***.***)
kirjoitti:

**Pull request merged**
