### PR TITLE
4.0 support

### PR DESCRIPTION
**Pull request by boostchicken**

### CODE REVIEW

**Comment by voxxit** [comment]
Hey @boostchicken! It seems that after this was merged, the podman install script no longer works. I am not sure when/how, but it seems like the link to `udmpro-podman-install.zip` on the IPFS node fails:

```shell
root@DreamMachinePro:/data/on_boot.d# ./00-podman.sh
downloading https://unifi.boostchicken.io/udmpro-podman-install.zip
download failed
```

I _do_ see a specific versions using a completely different naming convention: [podman-udmse-udmpro-v2023-04-17-bbf5.zip](https://unifi.boostchicken.io/podman-udmse-udmpro-v2023-04-17-bbf5.zip) -- should this script be updated to support that convention, or is some mapping somewhere that isn't apparent borked?

Thanks!

**Comment by llaforest** [comment]
> Hey @boostchicken! It seems that after this was merged, the podman install script no longer works. I am not sure when/how, but it seems like the link to `udmpro-podman-install.zip` on the IPFS node fails:
> 
> ```shell
> root@DreamMachinePro:/data/on_boot.d# ./00-podman.sh
> downloading https://unifi.boostchicken.io/udmpro-podman-install.zip
> download failed
> ```
> 
> I _do_ see a specific versions using a completely different naming convention: [podman-udmse-udmpro-v2023-04-17-bbf5.zip](https://unifi.boostchicken.io/podman-udmse-udmpro-v2023-04-17-bbf5.zip) -- should this script be updated to support that convention, or is some mapping somewhere that isn't apparent borked?
> 
> Thanks!

I have the same download failed on my UDM Pro on the 4.x OS and on my UDM SE that is still on 3.x... Any clue how to fix this?

**Comment by Ed-Ed-Ed** [comment]
> > Hey @boostchicken! It seems that after this was merged, the podman install script no longer works. I am not sure when/how, but it seems like the link to `udmpro-podman-install.zip` on the IPFS node fails:
> > ```shell
> > root@DreamMachinePro:/data/on_boot.d# ./00-podman.sh
> > downloading https://unifi.boostchicken.io/udmpro-podman-install.zip
> > download failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I _do_ see a specific versions using a completely different naming convention: [podman-udmse-udmpro-v2023-04-17-bbf5.zip](https://unifi.boostchicken.io/podman-udmse-udmpro-v2023-04-17-bbf5.zip) -- should this script be updated to support that convention, or is some mapping somewhere that isn't apparent borked?
> > Thanks!
> 
> I have the same download failed on my UDM Pro on the 4.x OS and on my UDM SE that is still on 3.x... Any clue how to fix this?
> 
> I tried to use the new zip file name, but even when extracted, the output folder is not as the script expect...

Any update on this one? Is there a new way of installing podman? 
I've tried {DESIRED_ZIPFILE} with new file name, podman-udmse-udmpro-v2024-01-11-0a66.zip, in the script as above, also updated the unzipping part with new file name as well. But failed with something went wrong message. :(

**Comment by m4n63** [comment]
> Any update on this one? Is there a new way of installing podman? I've tried {DESIRED_ZIPFILE} with new file name, podman-udmse-udmpro-v2024-01-11-0a66.zip, in the script as above, also updated the unzipping part with new file name as well. But failed with something went wrong message. :(

No, but you can use nspawn instead on 3-x and later
https://github.com/unifi-utilities/unifios-utilities/tree/main/nspawn-container

**Pull request merged**
