### PR TITLE
Updated script to support UDM/UDMPro 2.x firmware

### PR DESCRIPTION
**Pull request by jinkang23**
Updated remote script to support UDM/UDM Pro 2.x firmware while preserving installation method for legacy UDM/UDM Pro 1.x firmware. 

I've tested this and it works for my UDM Pro firmware 2.4.23. 

For more details, refer to [#416](https://github.com/unifi-utilities/unifios-utilities/issues/416)

### CODE REVIEW

**Comment by StiviiK** [comment]
I think the message which device was detected could be a bit improved. 
I am thinking of something like:
- UDM/UDMP version <2.0.0 was detected
- UDR/UDM/UDMP/UDMSE version >2.0.0 was detected

**Comment by jinkang23** [comment]
> I think the message which device was detected could be a bit improved. I am thinking of something like:
> 
> * UDM/UDMP version <2.0.0 was detected
> * UniFi Router version >2.0.0 was detected

Thanks for the feedback. I've updated the script to echo the exact device model and version detected.

**Review by operinko — APPROVED** [review]

**Review by magicdude4eva — APPROVED** [review]
Verified working on UDM Pro 2.4.23:
```
  _   _ ___  __  __   ___           _
 | | | |   \|  \/  | | _ ) ___  ___| |_
 | |_| | |) | |\/| | | _ \/ _ \/ _ \  _|
  \___/|___/|_|  |_| |___/\___/\___/\__|

 Execute any script when your udm system
 starts.

UniFi Dream Machine Pro version 2.4.23 was detected
Installing on-boot script...
Failed to disable unit: Unit file udm-boot.service does not exist.
Creating systemctl service file
Enabling UDM boot...
Created symlink /etc/systemd/system/multi-user.target.wants/udm-boot.service → /etc/systemd/system/udm-boot.service.
UDM Boot Script installed

Downloading CNI plugins script...
CNI plugins script installed
Executing CNI plugins script...
Downloading https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-arm64-v1.1.1.tgz.sha256
Downloading https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-arm64-v1.1.1.tgz
Pouring /data/.cache/cni-plugins/cni-plugins-linux-arm64-v1.1.1.tgz

Downloading CNI bridge script...
CNI bridge script installed
Executing CNI bridge script...
/data/on_boot.d/06-cni-bridge.sh

On boot script installation finished

You can now place your scripts in `/data/on_boot.d`
```

**Review by magicdude4eva — APPROVED** [review]

**Review by NimlothPL — APPROVED** [review]

**Review by janknieling — APPROVED** [review]
I can confirm that it is working at the Dream Machine Pro with Firmware v.1.7.X and 2.4.X

**Comment by pshirshov** [comment]
Worked for me too, please merge.

**Review by gatesry — APPROVED** [review]

**Comment by boostchicken** [comment]
You guys are miracle workers.  Warms my heart.

**Pull request merged**
