### PR TITLE
Auto set correct data path

### PR DESCRIPTION
**Pull request by bruvv**

### CODE REVIEW

**Comment by boostchicken** [comment]
holy shit dude.  I was putting this off till I upgraded to 2.  I just did and came here and see  this.  Thank you so much.  If you are ever in Socal drop me a line, food and beer for you :)

**Comment by bruvv** [comment]
No worries, was a relaxing day at the office so I had some time left over ;)
Where is socal ;) ?

**Comment by boostchicken** [comment]
I made a new branch called 1.12.x.  All the 1.0 format stuff stays and gets updated there.  main is now 2.5 or over

**Comment by bruvv** [comment]
Good thinking! I will once again go through it, it was a lot of change so I might have missed some stuff here and there.

**Pull request merged**
